# Generated by Django 4.2.11 on 2024-11-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
    ]
